[package]
name = "spec"
version = "1.0.0"
edition = "2021"

[dependencies]
# TODO: remove extra traits
syn = { version = "2.0.106", features = ["full"] }
proc-macro2 = "1.0.101"
quote = "1.0.40"

[lib]
proc-macro = true
