[package]
name = "specialize-fn"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: remove extra traits
syn = { version = "2.0.82", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.89"
quote = "1.0.37"

[lib]
proc-macro = true
